### ISSUE TITLE
Font filename issue on android

### ISSUE THREAD

**Issue by jpdutoit** [brightcove-archive/ooyala_native-skin#420]
On android, `fontawesome-webfont.ttf` has to be renamed to `fontawesome.ttf` for the playhead position indicator to appear.

**Comment by lental** [comment]
good point.  Instead of fixing the font, I ended up removing fontawesome from our code once and for all. (https://github.com/ooyala/native-skin/pull/424)  This should solve that issue, and remove any headaches from fontawesome going forward.

Thanks,
Mike

**Comment by lental** [comment]
fixed in latest stuff (#424)
