### ISSUE TITLE
How to Run the Sample Application?

### ISSUE THREAD

**Issue by erseno** [brightcove-archive/ooyala_native-skin#490]
Hello

I wish to try out the OoyalaSkinSampleApp.
I downloaded the zip file, and opened the project.

However, the lib files are not present in the sample so it will not build 

The instructions here say, it should just run

https://github.com/ooyala/native-skin/blob/stable/dev_docs/README-android.md#how-to-run-the-sample-application 

Not sure what im doing wrong

**Comment by lental** [comment]
hey @erseno , Did you try going into the android or iOS sample apps? https://github.com/ooyala/android-sample-apps/tree/stable/OoyalaSkinSampleApp

you should be able to run the app immediately from android studio. 

Libraries are not in the app when you clone for the first time, but running the gradle scripts automatically copies the necessary files from the vendor folders. (see https://github.com/ooyala/android-sample-apps/blob/stable/OoyalaSkinSampleApp/app/build.gradle)

**Comment by brol1dev** [comment]
@erseno, let us know if you were able to make the app work, I'll leave this issue open today and close it tomorrow if there's no answer.

Thanks!

**Comment by erseno** [comment]
Hi sorry for the late reply. 
It is working now, thanks. I did not realise the lib files and assets where in the vender folder
