### ISSUE TITLE
skin SDK in Fragment?

### ISSUE THREAD

**Issue by jayspringfield** [brightcove-archive/ooyala_native-skin#497]
Will the skin SDK work inside of a Fragment?  I've got my player layout inside of a fragment and I'm not able to move it.  The instructions only indicate what to do for activities.  If I try placing it in a fragment, I get errors from inside of React when it is looking for a FragmentManager.

**Comment by brol1dev** [comment]
1. What do you mean that you're not able to move it? You mean you can't play videos?
2. What errors do you get?
3. We didn't certificate the player within fragments, if it isn't working we might need to add code to support it. This depends on what errors you found.

**Comment by jayspringfield** [comment]
1. Sorry, mistyped there.  I meant I'm not able to use it.  The app crashes as soon as I try to play a video.

2 & 3.  I'll paste a stack trace below.  The app hangs before eventually reporting an ANR.  I'm following the instructions for updating an existing application here: https://github.com/ooyala/native-skin/blob/stable/dev_docs/README-android.md

10-18 14:25:04.051 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
10-18 14:25:04.051 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
10-18 14:25:04.051 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
10-18 14:25:04.061 8109-8109/com.telstra.nrl V/MediaPlayer: setVideoSurfaceTexture
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
10-18 14:25:04.061 8109-8109/com.telstra.nrl V/MediaPlayer-JNI: setAudioStreamType: 3
10-18 14:25:04.061 8109-8109/com.telstra.nrl V/MediaPlayer: MediaPlayer::setAudioStreamType
10-18 14:25:04.061 8109-8109/com.telstra.nrl V/MediaPlayer: setVideoSurfaceTexture
10-18 14:25:04.061 8109-8109/com.telstra.nrl V/MediaPlayer: prepareAsync
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
10-18 14:25:04.061 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
10-18 14:25:04.071 8109-8124/com.telstra.nrl D/MediaHTTPConnection: setReadTimeOut =  300000000ms
10-18 14:25:04.071 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
10-18 14:25:04.071 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
10-18 14:25:04.071 8109-8120/com.telstra.nrl D/MediaHTTPConnection: setReadTimeout with 300000000ms
10-18 14:25:04.071 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
10-18 14:25:04.071 8109-8120/com.telstra.nrl I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-18 14:25:04.071 8109-8120/com.telstra.nrl I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
10-18 14:25:04.081 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
10-18 14:25:04.081 8109-8109/com.telstra.nrl W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 8109
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageViewManager
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageShadowNode
10-18 14:25:04.091 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
10-18 14:25:04.101 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
10-18 14:25:04.101 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
10-18 14:25:04.101 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
10-18 14:25:04.101 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
10-18 14:25:04.101 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.ooyala.android.skin.view.ClosedCaptionsViewManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.ooyala.android.skin.view.CountdownViewManager
10-18 14:25:04.111 8109-8225/com.telstra.nrl W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.ooyala.android.skin.view.VolumeViewManager
10-18 14:25:04.211 8109-8109/com.telstra.nrl D/AndroidRuntime: Shutting down VM
10-18 14:25:04.211 8109-8109/com.telstra.nrl V/NRL: Exception type (class java.lang.AssertionError) reason (Uncaught exception) message (Attached DialogModule to host with pending alert but no FragmentManager (not attached to an Activity).) cause (null)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err: java.lang.AssertionError: Attached DialogModule to host with pending alert but no FragmentManager (not attached to an Activity).
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.modules.dialog.DialogModule.onHostResume(DialogModule.java:201)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:157)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl.moveToResumedLifecycleState(ReactInstanceManagerImpl.java:561)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(ReactInstanceManagerImpl.java:907)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:730)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl.access$800(ReactInstanceManagerImpl.java:102)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:208)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:181)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.os.AsyncTask.access$500(AsyncTask.java:180)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.os.Looper.loop(Looper.java:158)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7224)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-18 14:25:04.211 8109-8109/com.telstra.nrl W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by brol1dev** [comment]
@jayspringfield, have you tried the OoyalaSkinSampleApp we have in our android-sample-apps repo (https://github.com/ooyala/android-sample-apps)?

Please do, we have an item there called "Resizable Skin Player" which has a player inside a fragment. Here's the part of the code pertinent to the fragment containing an OoyalaPlayer: https://github.com/ooyala/android-sample-apps/blob/stable/OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/utils/fragments/SkinPlayerFragment.java

Please try it and let us know how it goes.

**Comment by jayspringfield** [comment]
Thanks.  I'll try it out and let you know.

**Comment by jayspringfield** [comment]
The main difference between the activity and Fragment examples is that the fragment requires you to call the onPause and onResume lifecycle methods for OoyalaSkinLayoutController.  Once I did that, it worked for me.
