### ISSUE TITLE
set player fullscreen by default?

### ISSUE THREAD

**Issue by jayspringfield** [brightcove-archive/ooyala_native-skin#499]
I'm looking at the [Skin player FAQ](http://support.ooyala.com/developers/documentation/reference/faq_api_sdk.html) which has an answer for this, but that answer won't compile.  It directs me to use the setFullscreen method on OoyalaPlayerLayoutController, but that controller isn't available to use with an OoyalaSkinLayout.  OoyalaSkinLayout has a setFullscreen method, but it's not public.  Is there a way to do this?

**Comment by lental** [comment]
I wouldn't suggest setting fullscreen to true by default.  What is your
behavior when you leave fullscreen?  what is the use case?

IMHO I would suggest that if you want fullscreen playback by default, to
create an activity that has all of the necessary immersive and status bar
flags set, then put the player into that activity's view, filling the
screen.

**Comment by jayspringfield** [comment]
I've done essentially what you're recommending, with a player that fills the screen and hiding the action bar, etc.  The video is fullscreen because the client I'm working for wants it to be that way, so I'm just trying to make it work.

The only issue I'm having is that since I can't set the player fullscreen by default, the OoyalaSkinLayout's toggleSystemUI method doesn't work properly because the fullscreen flag isn't set properly.

**Comment by lental** [comment]
Could you remove the fullscreen button, and let end-users use the back
button to leave the fullscreen activity?

the player's fullscreen functionality is more about filling the parent view
and not filling the view.  Is there any reason you need the button to be in
the UI?

**Comment by jayspringfield** [comment]
Yeah, if the player will work with the fullscreen button removed from the
skin. json file i can do that.  Toggling the system UI still won't work
though.  What flags are your setting in that method?  I can set them myself
as a workaround.

**Comment by lental** [comment]
I'm suggesting that you "toggle" by going into the fullscreen activity, and then using the back button to go back to the activity before video playback.  Does that match your workflow?

**Comment by jayspringfield** [comment]
Yes, the back button workflow is fine.  The reason I was hoping to still toggle the full screen state was to keep the player state consistent and to support hiding the status bar.  It seems like you guys don't care about the state and I was able to hide the status bar properly using the info from [here](https://developer.android.com/training/system-ui/immersive.html#nonsticky).

**Comment by lental** [comment]
I can definitely appreciate the player state consistency, but going into fullscreen for us lass about setting the correct visibility flags, and more about flooding the parent layout: https://github.com/ooyala/native-skin/blob/stable/sdk/android/ooyalaSkinSDK/src/main/java/com/ooyala/android/skin/OoyalaSkinLayout.java#L125

We don't have any way to start the player in fullscreen, and if we did, I feel like the use case for the developer would be limited - Do you really want the player to go into "smaller"/"inline" view when the end-user presses the fullscreen close button?  What other UI do you intend to show in the parent when the player goes from fullscreen to inline?

I'm not against adding configurations for starting fullscreen, I'm just afraid the results wouldn't be to your expectation.  If you're interested, let me know if you actually would want the above-explained behavior and what you're thinking

Thanks,
Mike

**Comment by jayspringfield** [comment]
Turns out there's a method to set the fullscreen status in the layout
controller, so i was able to use that
