### ISSUE TITLE
Put React SDK on NPM

### ISSUE THREAD

**Issue by kkemple** [brightcove-archive/ooyala_native-skin#501]
It seems really strange not to host this SDK in NPM where i can then just be included in a project. 

Currently there is a lot of heavy lifting needed to be done to get this work to work properly.

The React Native workflow is normally `npm install <module> && react-native link <module>`

**Comment by brol1dev** [comment]
We're exploring this approach. We see the benefit for users, but we can tell you that it isn't a trivial thing to do right now. We'll let you know how this one goes.

**Comment by jordan-goo** [comment]
@rcvrgs Do you have any updates on this? alternatively, a sample react native project with this integrated would be very helpful.

**Comment by neiker** [comment]
Any news on this?

/cc @IvanSakharovskii @MarkEPAM @AlinaVoronkovaEpam

**Comment by loginov-rocks** [comment]
That's not possible, since it's not a package, but an app. My team tried to inject Skin SDK as a Native Component into the another React Native project, but got no luck, it requires a lot of effort.

FYI: @DmitriiMaslov
