### ISSUE TITLE
Ooyala Player Immersive Mode in Galaxy S8/S8+ screen: Does not use the full screen

### ISSUE THREAD

**Issue by dbshe** [brightcove-archive/ooyala_native-skin#531]
We recently updated the Ooyala player and ooyala skin sdk to 4.25.0 [prev version 4.21.0]. Even after the update we could not play the videos to use the full screen. We could see the black bars on the side. Is there any way we can play the video with full screen and use the 18.5:9 aspect ratio [without the black bars and fit the screen].

**Comment by maxkupetskii** [comment]
@dbshe please, reopen if it's still an issue
