### ISSUE TITLE
NullPointerException at 'params.toString()'

### ISSUE THREAD

**Issue by nichucs** [brightcove-archive/ooyala_native-skin#666]
Please put a null check before executing this line of code:

https://github.com/ooyala/native-skin/blob/8cb42a683657996e358f2743a7567d30f39cf7d7/sdk/android/skin/src/main/java/com/ooyala/android/skin/OoyalaReactBridge.java#L42

Detailed Logs: http://crashes.to/s/b38fe46acde

**Comment by brol1dev** [comment]
Thanks for the finding. We'll fix it as soon as we can.

**Comment by akshaydch11** [comment]
This has been in fixed in 4.36 release. Closing this issue.
